server:
  port: 8763
spring:
  application:
    name: api
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/
    prefix:
    suffix: ./html
dubbo:
  registry:
    address: zookeeper://172.10.4.127:2181
  cloud:
    subscribed-services: ${provider.application.name}
provider:
  application:
    name: core-service
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always

media:
  master:
    datasource:
      url: jdbc:mysql://localhost:3306/master_tenant?useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      maxPoolSize: 10
      idleTimeout: 300000
      minIdle: 10
      poolName: master-database-connection-pool
  logging:
    level:
      root: warn
      org:
        springframework:
          web: debug
        hibernate: debug



